plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation (
            "com.codeborne:selenide:6.19.1",
            "org.junit.jupiter:junit-jupiter:5.9.3",
            'com.github.javafaker:javafaker:1.0.2',
            'io.qameta.allure:allure-selenide:2.29.0',
            'io.qameta.allure:allure-junit5:2.29.0'
    )
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
}
